spacebit_user_home:
    path:     /
    defaults: { _controller: SpacebitUserBundle:Default:home }

spacebit_user_login:
    path:     /login
    defaults: { _controller: SpacebitUserBundle:Default:login }

spacebit_user_signup:
    path:     /signup
    defaults: { _controller: SpacebitUserBundle:Default:signup }

spacebit_user_forgot_password:
    path:     /forgotPassword
    defaults: { _controller: SpacebitUserBundle:Default:forgotPassword }

spacebit_user_validate:
    path:     /validateUser
    defaults: { _controller: SpacebitUserBundle:Default:validateUser }
    methods:  ['POST']

spacebit_user_add:
    path:     /addUser
    defaults: { _controller: SpacebitUserBundle:Default:addUser }
    methods:  ['GET']