spacebit_user_login:
    path:     /login
    defaults: { _controller: SpacebitUserBundle:Default:login }

spacebit_user_signup:
    path:     /signup
    defaults: { _controller: SpacebitUserBundle:Default:signup }

spacebit_user_logout:
    path:     /logout
    defaults: { _controller: SpacebitUserBundle:Default:logout }

spacebit_user_forgot_password:
    path:     /forgotPassword
    defaults: { _controller: SpacebitUserBundle:Default:forgotPassword }

spacebit_user_profile:
    path:     /myProfile
    defaults: { _controller: SpacebitUserBundle:Default:myProfile }

spacebit_user_validate:
    path:     /validateUser
    defaults: { _controller: SpacebitUserBundle:Default:validateUser }
    methods:  ['POST']

spacebit_user_add:
    path:     /addUser
    defaults: { _controller: SpacebitUserBundle:Default:addUser }
    methods:  ['POST']

spacebit_load_departments:
    path:     /loadDepartments
    defaults: { _controller: SpacebitUserBundle:Default:loadDepartments }
    methods:  ['POST']

spacebit_check_user_availability:
    path:     /checkUserAvailability
    defaults: { _controller: SpacebitUserBundle:Default:checkUserAvailability }
    methods:  ['POST']

