spacebit_resources_home:
    path:     /
    defaults: { _controller: SpacebitResourcesBundle:Default:home }

spacebit_resources_equipment:
    path:     /equipment
    defaults: { _controller: SpacebitResourcesBundle:Default:equipment }

spacebit_resources_venues:
    path:     /venues
    defaults: { _controller: SpacebitResourcesBundle:Default:venues }