spacebit_resources_home:
    path:     /
    defaults: { _controller: SpacebitResourcesBundle:Default:home }



spacebit_resources_equipment:
    path:     /equipment
    defaults: { _controller: SpacebitResourcesBundle:Equipment:equipment }

spacebit_resources_equipment_get_departments:
    path:     /equipment/getDepartments
    defaults: { _controller: SpacebitResourcesBundle:Equipment:getDepartments }
    methods:  ['POST']

spacebit_resources_equipment_get_by_category:
    path:     /equipment/getByCategory
    defaults: { _controller: SpacebitResourcesBundle:Equipment:getByCategory }
    methods:  ['POST']

spacebit_resources_equipment_get_from_category:
    path:     /equipment/getFromCategory
    defaults: { _controller: SpacebitResourcesBundle:Equipment:getFromCategory }
    methods:  ['GET']



spacebit_resources_venues:
    path:     /venues
    defaults: { _controller: SpacebitResourcesBundle:Venues:venues }



spacebit_resources_vehicles:
    path:     /vehicles
    defaults: { _controller: SpacebitResourcesBundle:Vehicles:vehicles }

spacebit_resources_vehicles_add_request:
    path:     /vehicles/addRequest
    defaults: { _controller: SpacebitResourcesBundle:Vehicles:addRequest }
    methods:  ['POST']

spacebit_resources_vehicles_get_by_category:
    path:     /vehicles/getByCategory
    defaults: { _controller: SpacebitResourcesBundle:Vehicles:getByCategory }
    methods:  ['POST']