spacebit_resources_home:
    path:     /
    defaults: { _controller: SpacebitResourcesBundle:Default:home }



spacebit_resources_equipment:
    path:     /equipment
    defaults: { _controller: SpacebitResourcesBundle:Equipment:equipment }



spacebit_resources_venues:
    path:     /venues
    defaults: { _controller: SpacebitResourcesBundle:Venues:venues }



spacebit_resources_vehicles:
    path:     /vehicles
    defaults: { _controller: SpacebitResourcesBundle:Vehicles:vehicles }

spacebit_resources_vehicles_add_request:
    path:     /vehicles/addRequest
    defaults: { _controller: SpacebitResourcesBundle:Vehicles:addRequest }
    methods:  ['POST']

spacebit_resources_vehicles_get_by_category:
    path:     /vehicles/getByCategory
    defaults: { _controller: SpacebitResourcesBundle:Vehicles:getByCategory }
    methods:  ['POST']