spacebit_admin_home:
    path:     /
    defaults: { _controller: SpacebitAdminBundle:Default:home }

spacebit_admin_sample:
    path:     /sample
    defaults: { _controller: SpacebitAdminBundle:Default:sample }

spacebit_admin_resource:
    path:     /resource
    defaults: { _controller: SpacebitAdminBundle:Default:resource}

spacebit_admin_resource_add_equipment:
    path:     /addEquipment
    defaults: { _controller: SpacebitAdminBundle:Default:addEquipment}
    methods:  ['POST']

spacebit_admin_resource_add_vehicle:
    path:     /addVehicle
    defaults: { _controller: SpacebitAdminBundle:Default:addVehicle}
    methods:  ['POST']

spacebit_admin_vehicle:
    path:     /vehicles
    defaults: { _controller: SpacebitAdminBundle:Default:vehicles}

spacebit_admin_resource_view_vehicle:
    path:     /getVehicleByPlateNo
    defaults: { _controller: SpacebitAdminBundle:Default:getVehicleByPlateNo}
    methods:  ['POST']