spacebit_admin_home:
    path:     /
    defaults: { _controller: SpacebitAdminBundle:Default:home }



spacebit_admin_user:
    path:     /users
    defaults: { _controller: SpacebitAdminBundle:User:users }

spacebit_admin_user_getByID:
    path:     /users/getByID
    defaults: { _controller: SpacebitAdminBundle:User:getDetails }
    methods:  ['POST']

spacebit_admin_user_activate:
    path:     /users/activate
    defaults: { _controller: SpacebitAdminBundle:User:activate }
    methods:  ['POST']

spacebit_admin_user_access_level_change:
    path:     /users/changeAccessLevel
    defaults: { _controller: SpacebitAdminBundle:User:changeAccessLevel }
    methods:  ['POST']

spacebit_admin_equipment:
    path:     /equipment
    defaults: { _controller: SpacebitAdminBundle:Equipment:equipment }

spacebit_admin_equipments_get_all:
    path:     /equipment/getAll
    defaults: { _controller: SpacebitAdminBundle:Equipment:getAll }

spacebit_admin_equipments_get_by_resource_id:
    path:     /equipment/getByResourceID
    defaults: { _controller: SpacebitAdminBundle:Equipment:getByResourceID }
    methods:  ['POST']

spacebit_admin_equipments_add_edit:
    path:     /equipment/addEdit
    defaults: { _controller: SpacebitAdminBundle:Equipment:addEdit }
    methods:  ['POST']

spacebit_admin_equipment_accept_request:
    path:     /equipment/changeRequest
    defaults: { _controller: SpacebitAdminBundle:Equipment:changeRequestStatus }
    methods:  ['POST']



spacebit_admin_venues:
    path:     /venues
    defaults: { _controller: SpacebitAdminBundle:Venues:venues }



spacebit_admin_vehicles:
    path:     /vehicles
    defaults: { _controller: SpacebitAdminBundle:Vehicles:vehicles }

spacebit_admin_vehicles_get_all:
    path:     /vehicles/getAll
    defaults: { _controller: SpacebitAdminBundle:Vehicles:getAll }

spacebit_admin_vehicles_get_by_plate_no:
    path:     /vehicles/getByPlateNo
    defaults: { _controller: SpacebitAdminBundle:Vehicles:getByPlateNo }
    methods:  ['POST']

spacebit_admin_vehicles_add_edit:
    path:     /vehicles/addEdit
    defaults: { _controller: SpacebitAdminBundle:Vehicles:addEdit }
    methods:  ['POST']

spacebit_admin_vehicles_request_get_all_group_names:
    path:     /vehicles/requests/getAllGroupNamesAndVehicles
    defaults: { _controller: SpacebitAdminBundle:Vehicles:getAllGroupNamesAndVehicles }
    methods:  ['POST']

spacebit_admin_vehicles_request_get_route:
    path:     /vehicles/requests/getRouteByGroupID
    defaults: { _controller: SpacebitAdminBundle:Vehicles:getRouteByGroupID }
    methods:  ['POST']

spacebit_admin_vehicles_request_change:
    path:     /vehicles/requests/change
    defaults: { _controller: SpacebitAdminBundle:Vehicles:changeRequestStatus }
    methods:  ['POST']